version: '3'
services:
  app-agenda:
    container_name: app-agenda
    build:
      context: .
      dockerfile: .docker/local/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - db-agenda
      - rabbitmq-agenda
    networks:
      - shared
    ports:
      - "${APP_PORT}:8080"
    environment:
      spring.datasource.url: jdbc:mysql://db-agenda:3306/${DB_DATABASE}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
  db-agenda:
    container_name: db-agenda
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./.docker/local/data/mysql:/var/lib/mysql
    ports:
      - "${DB_EXT_PORT}:3306"
    networks:
      - shared
  rabbitmq-agenda:
    container_name: rabbitmq-agenda
    image: rabbitmq:3.8.3-management
    restart: unless-stopped
    ports:
      - "${RABBITMQ_EXTERNAL_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_EXTERNAL_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - shared
networks:
  shared:
    external: true